[package]
name = "gareji-board-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
gareji-board-core.workspace = true
gareji-board-domain.workspace = true
gareji-board-store.workspace = true
serde.workspace = true
tauri = { version = "2.11.5" }

[build-dependencies]
tauri-build = { version = "2.6.3" }

[lints]
workspace = true
